### ISSUE TITLE
Clicking on size input in new file dialog does not select whole text

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#284]
Basically title, when you click on size input, it should select whole text

**Comment by Equbuxu** [comment]
I've intentionally changed this behavior in the canvas size input because it makes it difficult to remove the selection if you want to edit the number (normally clicking on the selection removes it but here you have to press 3 times before it's actually removed). I've kept it in the other fields (brush size) where it's actually convenient. 

I've also just tested aseprite, paint.net, clip studio paint, krita, and ms paint. None have the same self-selecting fields, however, some do have the text in the first field selected by default which lets you type in your own value right away. I suggest that we do that instead of selecting on click.

**Comment by CPKreuz** [comment]
I now made it so that the new file dialog select's the width picker first, after that when the user presses enter it selects the height picker and after another enter it select's the Create button

So you can just Enter your way through there now

I actually prefer the select all text behavior way more over having to press Ctrl + A every time

**Comment by Equbuxu** [comment]
> I now made it so that the new file dialog select's the width picker first, after that when the user presses enter it selects the height picker and after another enter it select's the Create button
> 
> So you can just Enter your way through there now
> 
> I actually prefer the select all text behavior way more over having to press Ctrl + A every time

Actually, enter shouldn't cycle through fields, enter should execute the default button of the dialog regardless of what field is focused. I think this is different from focus

**Comment by Equbuxu** [comment]
As it turns out WPF has a default button feature, you just set IsDefault to true

**Comment by CPKreuz** [comment]
Imagine using built in stuff and not doing everything from scratch
