### ISSUE TITLE
Crash after undoing merge

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#292]
Open [save1.zip](https://github.com/PixiEditor/PixiEditor/files/7724663/save1.zip), select new layer 9, merge with below, undo

**Comment by flabbet** [comment]
I fixed this for undo, but not for redo. Groups probably lose valid Guids. Not sure if this happens in ReverseProcess or Process (Undo or Redo). I suspect it is `InsertAt` in ReverseProcess (`InsertAtProcess`), because it does raw Layers insertion, without doing anything with group. Although it should work, since loaded layers have same the guid. Further debugging is required

**Comment by flabbet** [comment]
Fixed
