### ISSUE TITLE
Fix all compile-time warnings

### ISSUE THREAD

**Issue by ArtemK123** [PixiEditor/PixiEditor#75]
**Describe as detailed as possible when it happens**
I cloned the repository and have built it for the first time. And I got a bunch of warnings. In my opinion, those warnings:
1. Give the contributor the possibility to write code with even more warnings
2. Make harder for the contributor to become ensure that the change will not break anything
3. Indicate to possible bugs, just like failed tests

**Describe what you tried to do in order to fix it**
Firstly, I tried not to make even more warnings. I can try to fix all of them by myself, but I think it is better to create the issue first in order to:
1. Ask for information about env-related issues, which are raised only on my machine
2. Not to clog the pull-request related to the other issue, which is under code review now.
3. Clearly define the scope of the changes

**Include screenshots of error**
![image](https://user-images.githubusercontent.com/31692671/95673712-e7be6c00-0bb3-11eb-9bf9-47fbbc449191.png)

**Additional context**
Maybe, some of the warnings are related to my local environment and may be fixed without changing the code. If so, please write to me about it.

**Comment by flabbet** [comment]
Unfortunately, we _can't_ fix them easily, all we can do is suppress them somehow. Since these warnings are an indication, that the libraries we use weren't built for .NET Core 3.1, It's okay, they work normally, but warnings are there. To fix this we would need to replace them with ones that are built for .NET Core 3.1 or write our own versions. This is very time-consuming. Before version 1.0 I would like to achieve this.

**Comment by ArtemK123** [comment]
I will try to investigate this after the issue [about the static analyzer ](https://github.com/PixiEditor/PixiEditor/issues/74)

Also, be ready for the whole bunch of new warnings after the analyzer is added.

**Comment by flabbet** [comment]
Sure

**Comment by ArtemK123** [comment]
Hi. Are those warnings still presented? If not, can I close this issue?
